"""baseline schema

Revision ID: 3e3a70149bb0
Revises: 
Create Date: 2026-06-29 14:43:24.057353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3a70149bb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('current_players', sa.Integer(), nullable=True),
    sa.Column('reviews_total', sa.Integer(), nullable=True),
    sa.Column('reviews_positive', sa.Integer(), nullable=True),
    sa.Column('review_score_desc', sa.String(length=64), nullable=True),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_snapshot_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_snapshot_collected_at'), ['collected_at'], unique=False)

    op.create_table('marketing_country',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('visits', sa.Integer(), nullable=False),
    sa.Column('pct', sa.Float(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'snapshot_date', 'country', name='uq_marketing_country')
    )
    with op.batch_alter_table('marketing_country', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketing_country_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketing_country_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('marketing_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=160), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'date', 'metric', 'source', name='uq_marketing_daily')
    )
    with op.batch_alter_table('marketing_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketing_daily_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketing_daily_date'), ['date'], unique=False)

    op.create_table('marketing_owners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('owners_pct', sa.Float(), nullable=True),
    sa.Column('non_owners_pct', sa.Float(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'snapshot_date', name='uq_marketing_owners')
    )
    with op.batch_alter_table('marketing_owners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketing_owners_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketing_owners_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('players_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('daily_active_users', sa.Integer(), nullable=False),
    sa.Column('peak_concurrent_users', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'date', name='uq_players_daily')
    )
    with op.batch_alter_table('players_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_daily_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_daily_date'), ['date'], unique=False)

    op.create_table('playtime_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('lifetime_users', sa.Integer(), nullable=True),
    sa.Column('avg_minutes', sa.Integer(), nullable=True),
    sa.Column('median_minutes', sa.Integer(), nullable=True),
    sa.Column('distribution', sa.JSON(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'snapshot_date', name='uq_playtime_snapshot')
    )
    with op.batch_alter_table('playtime_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playtime_snapshot_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playtime_snapshot_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('raw_payload',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_payload', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_payload_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_payload_collected_at'), ['collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_payload_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_payload_source'), ['source'], unique=False)

    op.create_table('review',
    sa.Column('recommendation_id', sa.String(length=32), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('voted_up', sa.Boolean(), nullable=False),
    sa.Column('votes_up', sa.Integer(), nullable=False),
    sa.Column('votes_funny', sa.Integer(), nullable=False),
    sa.Column('playtime_at_review_min', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_created_at'), ['created_at'], unique=False)

    op.create_table('sales_by_country',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('sku', sa.String(length=160), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=160), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('net_units', sa.Integer(), nullable=False),
    sa.Column('net_sales_usd', sa.Float(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'country', 'sku', 'platform', name='uq_sales_by_country')
    )
    with op.batch_alter_table('sales_by_country', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_by_country_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_by_country_package_id'), ['package_id'], unique=False)

    op.create_table('traffic_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=160), nullable=False),
    sa.Column('feature', sa.String(length=160), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('visits', sa.Integer(), nullable=False),
    sa.Column('owner_impressions', sa.Integer(), nullable=False),
    sa.Column('owner_visits', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'date', 'category', 'feature', name='uq_traffic_daily')
    )
    with op.batch_alter_table('traffic_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_daily_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_daily_date'), ['date'], unique=False)

    op.create_table('wishlist_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('adds', sa.Integer(), nullable=False),
    sa.Column('deletes', sa.Integer(), nullable=False),
    sa.Column('purchases_activations', sa.Integer(), nullable=False),
    sa.Column('gifts', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'date', name='uq_wishlist_daily')
    )
    with op.batch_alter_table('wishlist_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_daily_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_daily_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_daily_date'))
        batch_op.drop_index(batch_op.f('ix_wishlist_daily_app_id'))

    op.drop_table('wishlist_daily')
    with op.batch_alter_table('traffic_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_daily_date'))
        batch_op.drop_index(batch_op.f('ix_traffic_daily_app_id'))

    op.drop_table('traffic_daily')
    with op.batch_alter_table('sales_by_country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_by_country_package_id'))
        batch_op.drop_index(batch_op.f('ix_sales_by_country_month'))

    op.drop_table('sales_by_country')
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_created_at'))
        batch_op.drop_index(batch_op.f('ix_review_app_id'))

    op.drop_table('review')
    with op.batch_alter_table('raw_payload', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_payload_source'))
        batch_op.drop_index(batch_op.f('ix_raw_payload_key'))
        batch_op.drop_index(batch_op.f('ix_raw_payload_collected_at'))
        batch_op.drop_index(batch_op.f('ix_raw_payload_app_id'))

    op.drop_table('raw_payload')
    with op.batch_alter_table('playtime_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playtime_snapshot_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_playtime_snapshot_app_id'))

    op.drop_table('playtime_snapshot')
    with op.batch_alter_table('players_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_daily_date'))
        batch_op.drop_index(batch_op.f('ix_players_daily_app_id'))

    op.drop_table('players_daily')
    with op.batch_alter_table('marketing_owners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketing_owners_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_marketing_owners_app_id'))

    op.drop_table('marketing_owners')
    with op.batch_alter_table('marketing_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketing_daily_date'))
        batch_op.drop_index(batch_op.f('ix_marketing_daily_app_id'))

    op.drop_table('marketing_daily')
    with op.batch_alter_table('marketing_country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketing_country_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_marketing_country_app_id'))

    op.drop_table('marketing_country')
    with op.batch_alter_table('game_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_snapshot_collected_at'))
        batch_op.drop_index(batch_op.f('ix_game_snapshot_app_id'))

    op.drop_table('game_snapshot')
    # ### end Alembic commands ###
